5 >= 1            // true
0 === 1           // false
4 <= 1            // false
1 != 1            // false
1 == "1"          // true
1 === "1"         // false
"2" == "2"        // true
"2" === "2"       // true
"12" !== 12       // true
"15" != 15        // false
"A" > "B"         // false
"B" < "C"         // true
"a" > "A"         // true
"b" < "A"         // false
"bee" > "bbe"           // true
"BeE" < "Bee"           // true
"SonTer" > "Soncom"            // false 
"circle" > "circles"           // false
"NaRuTo" < "nArUtO"            // true
true === false            // false
true != true            // false